In [15]:
from sklearn.linear_model import HuberRegressor
# from sklearn.linear_model import LinearRegressor

X_train = [[6],[7],[7.5]]
Y_train = [6,7,7.5]

huber = HuberRegressor()
huber.fit(X_train,Y_train)
y_huber_pred_huber = huber.predict([[90]])

# lr = LinearRegressor()
# lr.fit(X_train,Y_train)
# y_lr_pred_huber = lr.predict(X_train)

print(y_huber_pred_huber) 
# print(y_lr_pred_huber) 

[90.00000804]


In [6]:
help(HuberRegressor.fit)

Help on function fit in module sklearn.linear_model.huber:

fit(self, X, y, sample_weight=None)
    Fit the model according to the given training data.
    
    Parameters
    ----------
    X : array-like, shape (n_samples, n_features)
        Training vector, where n_samples in the number of samples and
        n_features is the number of features.
    
    y : array-like, shape (n_samples,)
        Target vector relative to X.
    
    sample_weight : array-like, shape (n_samples,)
        Weight given to each sample.
    
    Returns
    -------
    self : object



### train_test_split

输入：
* 要划分的数据 𝐗,𝐲
* 校验集的大小(test_size)
* 随机种子(random_state)

输出：
* 𝐗,𝐲的训练集和校验集

**注意：这里用test表示校验集**

In [2]:
from sklearn.model_selection import train_test_split
import numpy as np

X,y = np.arange(10).reshape((5,2)),range(5)
print(X)
print(y)
list(y)

print("\n---------------------\n")
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)
print(X_train)
print("\n----------\n")
print(X_test)
print("\n----------\n")
print(y_train)
print("\n----------\n")
print(y_test)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
range(0, 5)

---------------------

[[4 5]
 [0 1]
 [6 7]]

----------

[[2 3]
 [8 9]]

----------

[2, 0, 3]

----------

[1, 4]


 # 波士顿房价数据探索
通过可视化手段探索数据特征

In [21]:
# 数据处理，矩阵相关
import numpy as np
# 数据分析
import pandas as pd 
# 数据可视化
import matplotlib.pyplot as plt
# 数据可视化
import seaborn as sb

#help('pandas.read_csv')
dataFrame = pd.read_csv("boston_housing.csv")
type(dataFrame)
#help('pandas.core.frame.DataFrame')
dataFrame.head()


CRIM  ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18   2.31     0  0.538  6.575  65.2  4.0900    1  296       15   
1  0.02731   0   7.07     0  0.469  6.421  78.9  4.9671    2  242       17   
2  0.02729   0   7.07     0  0.469  7.185  61.1  4.9671    2  242       17   
3  0.03237   0   2.18     0  0.458  6.998  45.8  6.0622    3  222       18   
4  0.06905   0   2.18     0  0.458  7.147  54.2  6.0622    3  222       18   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [27]:
print(range(5))
print(range(2,6))
print(list(range(5)))
type(range(5))


range(0, 5)
range(2, 6)
[0, 1, 2, 3, 4]


range