# 数组 

## 数组的创建与使用

In [2]:
import numpy as np # np.作为开头

array = np.array([[1,2,3,4,5],[2,2,2,2,2],list(range(5)),list(range(2,7))])

print(array)

[[1 2 3 4 5]
 [2 2 2 2 2]
 [0 1 2 3 4]
 [2 3 4 5 6]]


In [2]:
type(array)

numpy.ndarray

In [3]:
array.shape

(4, 5)

In [4]:
array.ndim

2

In [5]:
array[1]

array([2, 2, 2, 2, 2])

In [6]:
array[-3]

array([2, 2, 2, 2, 2])

In [7]:
array[2:4]

array([[0, 1, 2, 3, 4],
       [2, 3, 4, 5, 6]])

In [8]:
array[-3] = 3
print(array)

[[1 2 3 4 5]
 [3 3 3 3 3]
 [0 1 2 3 4]
 [2 3 4 5 6]]


In [9]:
array[-3] = [6,6,6,6,6]
print(array)

[[1 2 3 4 5]
 [6 6 6 6 6]
 [0 1 2 3 4]
 [2 3 4 5 6]]


## 一维数组 

In [10]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
arr[3]

3

In [12]:
arr[-3]

7

In [13]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [14]:
arr[3:8] = -2
print(arr)

[ 0  1  2 -2 -2 -2 -2 -2  8  9]


## 多维数组

In [15]:
arr2 = np.arange(24).reshape(2,3,4)
print(arr2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
arr2[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
arr2[0,2,1:]

array([ 9, 10, 11])

In [18]:
arr2[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [19]:
arr2[0,0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [20]:
arr2[0,::2,::2]

array([[ 0,  2],
       [ 8, 10]])

In [21]:
arr2[0,::2,1:4:2]

array([[ 1,  3],
       [ 9, 11]])

In [22]:
arr2[[0,0,0,0],[0,0,2,2],[0,2,0,2]]

array([ 0,  2,  8, 10])

In [23]:
help(np.ix_)

Help on function ix_ in module numpy:

ix_(*args)
    Construct an open mesh from multiple sequences.
    
    This function takes N 1-D sequences and returns N outputs with N
    dimensions each, such that the shape is 1 in all but one dimension
    and the dimension with the non-unit shape value cycles through all
    N dimensions.
    
    Using `ix_` one can quickly construct index arrays that will index
    the cross product. ``a[np.ix_([1,3],[2,5])]`` returns the array
    ``[[a[1,2] a[1,5]], [a[3,2] a[3,5]]]``.
    
    Parameters
    ----------
    args : 1-D sequences
        Each sequence should be of integer or boolean type.
        Boolean sequences will be interpreted as boolean masks for the
        corresponding dimension (equivalent to passing in
        ``np.nonzero(boolean_sequence)``).
    
    Returns
    -------
    out : tuple of ndarrays
        N arrays with N dimensions each, with N the number of input
        sequences. Together these arrays form an open mesh.

In [24]:
arr2[np.ix_([0],[0,2],[0,2])]

array([[[ 0,  2],
        [ 8, 10]]])

# 矩阵

## 常见矩阵的创建

In [25]:
data1 = np.matrix(np.zeros((3,3)))
print(data1)
type(data1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


numpy.matrix

In [26]:
print(data1.ndim,data1.shape,sep='\n')

2
(3, 3)


In [27]:
data2 = np.matrix(np.ones((2,4)))
print(data2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
data3 = np.matrix(np.random.rand(3,4))
print(data3)

[[0.54780226 0.29399729 0.68623252 0.56409358]
 [0.20854301 0.82177424 0.33764795 0.80435683]
 [0.24222966 0.66452615 0.80133835 0.00106646]]


In [29]:
#randint(low,high=none,size = None)
data4 = np.matrix(np.random.randint(5,size=(2,3)))
print(data4)

[[1 1 2]
 [1 0 0]]


In [30]:
#randint(low,high=none,size = None)
data5 = np.matrix(np.random.randint(2,16,size=(3,5)))
print(data5)

[[14  6  5  4  3]
 [14  2 14 14  4]
 [ 4  5 15 10  4]]


In [31]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [32]:
data6 = np.eye(3,k=-1)
print(data6)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [33]:
a1 = [2,3,4]
a2 = np.matrix(np.diag(a1,k=1))
print(a2)

[[0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]
 [0 0 0 0]]


## 矩阵的合并

### np.vstack

In [34]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    hstack

In [35]:
arr3 = np.array([3,4,5])
arr4 = np.array([[4,5,6],
                 [5,6,7]])
arr34 = np.vstack((arr3,arr4))
print(arr34)

[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [36]:
arr5 = np.arange(24).reshape(2,3,4)
arr6 = np.arange(36).reshape(3,3,-1) # -1表示通配，不知道有多少列，让计算机自己算
arr56 = np.vstack((arr5,arr6))
print(arr5,arr6,arr56,sep = '\n----------------------\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
----------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
----------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


### np.hstack

In [37]:
arr7 = arr5.reshape(3,2,4)
arr8 = arr6
arr78 = np.hstack((arr7,arr8))
print(arr7,arr8,arr78,sep='\n----------------------\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
----------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
----------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 8  9 10 11]
  [12 13 14 15]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [38]:
#np.dstack()

### np.concatenate

In [39]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
   

In [5]:
arr9 = np.arange(30,36).reshape(3,2)
arr10 = np.arange(0,6).reshape(2,3)
arr11 = np.expand_dims(arr9,axis=0)
arr12 = np.expand_dims(arr10,axis=1)
print(arr9,arr10,arr11,arr12,sep='\n----------------------\n')

[[30 31]
 [32 33]
 [34 35]]
----------------------
[[0 1 2]
 [3 4 5]]
----------------------
[[[30 31]
  [32 33]
  [34 35]]]
----------------------
[[[0 1 2]]

 [[3 4 5]]]


In [41]:
print(arr9.shape,arr10.shape,arr11.shape,arr12.shape,sep='\n----------------------\n')

(3, 2)
----------------------
(2, 3)
----------------------
(1, 3, 2)
----------------------
(2, 1, 3)


In [6]:
arr910T = np.concatenate((arr9,arr10.T),axis=0)
print(arr9,arr10.T,arr910T,sep='\n----------------------\n')

[[30 31]
 [32 33]
 [34 35]]
----------------------
[[0 3]
 [1 4]
 [2 5]]
----------------------
[[30 31]
 [32 33]
 [34 35]
 [ 0  3]
 [ 1  4]
 [ 2  5]]


In [43]:
arr910T1 = np.concatenate((arr9,arr10.T),axis=1)
print(arr9,arr10.T,arr910T1,sep='\n----------------------\n')

[[30 31]
 [32 33]
 [34 35]]
----------------------
[[0 3]
 [1 4]
 [2 5]]
----------------------
[[30 31  0  3]
 [32 33  1  4]
 [34 35  2  5]]


# broadcasting 广播

1. 所有数组都向其中shape最长的数组看齐
    3x3x4 1x1x4
2. 输出数组的shape是输入数组shape的各个轴上的最大值
    7x1x8 1x5x1 
    输出：7x5x8
    7x2x8 1x5x1 
    输出：7x5x8
3. 输入数组的某个轴长度相同或者有1的时候，这个数组才能够用来计算，否则报错
4. 输入数组的某个轴的长度为1时，沿着此轴运算时都用这个轴上的第一组值

In [44]:
x = np.arange(4).reshape(4,1)
y = np.ones(5)
print(x,y,x+y,sep='\n-------------\n')

[[0]
 [1]
 [2]
 [3]]
-------------
[1. 1. 1. 1. 1.]
-------------
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [45]:
x = np.arange(4).reshape(4,1)
y = [1,1,1,1,1]
print(x,y,x+y,sep='\n-------------\n')

[[0]
 [1]
 [2]
 [3]]
-------------
[1, 1, 1, 1, 1]
-------------
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


## IO （数组的保存和读取）

In [46]:
arr1 = np.array(list(range(18))).reshape(3,-1)
arr2 = np.random.randint(5,size=(2,3))
arr3 = np.arange(0, 1, 0.1)
arr4 = np.sin(arr3)
arr5 = np.cos(arr3)

### numpy.save() & np.load()

In [47]:
np.save('data/arr1',arr1)

In [48]:
x = np.load('data/arr1.npy')
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


### np.savez & np.load()

In [49]:
np.savez('data/arr1-5',arr1,arr2,arr3,sin_array = arr4,cons_arr = arr5)

In [50]:
arrs = np.load('data/arr1-5.npz')
print(arrs.files)

['sin_array', 'cons_arr', 'arr_0', 'arr_1', 'arr_2']


In [51]:
print(arrs['arr_0'],arrs['arr_1'],arrs['arr_2'],arrs['sin_array'],arrs['cons_arr'],sep = '\n----------------------\n')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
----------------------
[[1 1 0]
 [1 2 3]]
----------------------
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
----------------------
[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]
----------------------
[1.         0.99500417 0.98006658 0.95533649 0.92106099 0.87758256
 0.82533561 0.76484219 0.69670671 0.62160997]


### savetxt() & np.loadtxt()

In [52]:
np.savetxt('data/arr1',arr1) # 不会自动加后缀txt

In [53]:
x = np.loadtxt('data/arr1') # 若不设置，默认以科学计数法保存，以空格分隔
print(x)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]]


In [56]:
np.savetxt('data/arr2.txt',arr2,fmt="%d",delimiter=",") # 设置保存为整数，以逗号分隔

In [57]:
x = np.loadtxt('data/arr2.txt',delimiter=",") # load 时也要指定为逗号分隔
print(x)

[[1. 1. 0.]
 [1. 2. 3.]]
