# 导入工具包

In [29]:
from mxnet import nd
import numpy as np

# 数据类型NDArray

## 创建NDArray

In [26]:
x = nd.arange(24)
a = x.reshape((2,3,4))
b = nd.ones((2,2,2))
c = nd.zeros((2,3,3))
d = nd.array([[1,1],[0,0]])
print(a,b,c,d, sep='\n-----------------\n')


[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>
-----------------

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
<NDArray 2x2x2 @cpu(0)>
-----------------

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
<NDArray 2x3x3 @cpu(0)>
-----------------

[[1. 1.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>


## NDArray的运算符

### 加减乘除 （略）

#### 广播机制

In [28]:
a = nd.arange(3).reshape(3,1)
b = nd.array([1,2])
c = a + b
d = a - b
e = a * b
f = a / b
print(a,b,c,d,e,f, sep='\n-----------------\n')


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>
-----------------

[1. 2.]
<NDArray 2 @cpu(0)>
-----------------

[[1. 2.]
 [2. 3.]
 [3. 4.]]
<NDArray 3x2 @cpu(0)>
-----------------

[[-1. -2.]
 [ 0. -1.]
 [ 1.  0.]]
<NDArray 3x2 @cpu(0)>
-----------------

[[0. 0.]
 [1. 2.]
 [2. 4.]]
<NDArray 3x2 @cpu(0)>
-----------------

[[0.  0. ]
 [1.  0.5]
 [2.  1. ]]
<NDArray 3x2 @cpu(0)>


### 矩阵乘、转置

In [21]:
X = nd.arange(12).reshape(3,4)
Y = nd.ones((3,4))
Z = nd.dot(X, Y.T)
print(X,Y,Z, sep='\n-----------------\n')


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>
-----------------

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>
-----------------

[[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]]
<NDArray 3x3 @cpu(0)>


### 连结（concatenate）

In [44]:
X = nd.arange(12).reshape(3,4)
Y = nd.ones((3,4))
Z1 = nd.concat(X, Y, dim=0)
Z2 = nd.concat(X, Y, dim=1)
print(X,Y,Z1,Z2, sep='\n-----------------\n')


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>
-----------------

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>
-----------------

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 6x4 @cpu(0)>
-----------------

[[ 0.  1.  2.  3.  1.  1.  1.  1.]
 [ 4.  5.  6.  7.  1.  1.  1.  1.]
 [ 8.  9. 10. 11.  1.  1.  1.  1.]]
<NDArray 3x8 @cpu(0)>


### 条件判断 (== > <)

In [47]:
X = nd.arange(4).reshape(2,2)
Y = nd.ones((2,2))
print(X,Y)
print(X == Y)
print(X > Y)
print(X < Y)


[[0. 1.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)> 
[[1. 1.]
 [1. 1.]]
<NDArray 2x2 @cpu(0)>

[[0. 1.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>

[[0. 0.]
 [1. 1.]]
<NDArray 2x2 @cpu(0)>

[[1. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>


## NDArray 和 Numpy 的相互转换

In [43]:
X = np.ones((2,2))
# Numpy 转为 NDArray
Y = nd.array(X)
# NDArray 转为 Numpy
Z = Y.asnumpy()
print(X,Y,Z, sep='\n-----------------\n')
print('\n-----------------\n')
print(type(X),type(Y),type(Z), sep='\n')

[[1. 1.]
 [1. 1.]]
-----------------

[[1. 1.]
 [1. 1.]]
<NDArray 2x2 @cpu(0)>
-----------------
[[1. 1.]
 [1. 1.]]

-----------------

<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>
<class 'numpy.ndarray'>
